sudo: false
cache: bundler
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
install: true
notifications:
  slack:
    secure: ZSO6yI0nxJw1tbHA6zjwZUkN66hP2qE5odINYIvcdpucCSigvrqor8tREyBK5l335IiWpcHnDMvtm198wf0YojXbWFdaRHP+asjnrIu7RGKkRquh0DaTBBXcuPBvs6xzgcxR4F/9vqcdhMojXGuAJ+jKD1EyJuqWH1mMheoBZQ94DduPM/srJ0/d7fnJLRXW7kZfzSUSNMgxqvs+cRyUJyM5Hcr0CydExeoD6iFIg5WjjiPReHmZ+hqbJSaKBDo0jC3PsRY7LPamuV6HiYkeHLCz6BRiQWnas49Eh0HIdptLfaUDEsEcB+ur8i/uoiCozquWO5AZoeIlviqmFKt/ElDxJk4wVKdnCY0Kvto1sxVrJGrreahNJsoQEtRV82n6cQJ22Cr5STXcV5SbabQdcb47d1Kosv2DG3FDGEitRNu7DsmSUgNTpFbeav7wF9wySQkxrlNabi5PAOSmqCIDq19iwxsOQYs59aexX6csJZjCoOe5ut/LtoniC/fWoBPLiIQb4WcAwHhqrGdXOhry+/ZYjtNukmobwYFODjNXgU+DOgQXfKHjAu9sCxhgtyjVsBYVOsgh2l0qjtalDRGdjl+cLYSd6iO+6VglP4ySq2ac2WXBqriNMY4s+vD+vW1KT7XgXOH0vamm8c9bRPydXEzOok58RtfJBTeXEwpET5g=
  email: false
#deploy:
#  provider: heroku
#  api_key:
#    secure: YSex4oF++D70Y49XLpoQ4wCuKkWAukNb+NbMJKG7cKP9HkBRzttlmLNIItjTkWrijsQ7KCSfh657xHfelXgGpfpMnQEOsVIY54Fk+OUi2Wz3k2Y6v5huZ2EHwhOw5xFFefYyfhRPTLejpHvv8qdz16z2c5fg4BgY0Gmnm6d3cUzToXTlScLDqHUVXXNjkMOXwC9qvqBOsLehkuZjYASGsiweA8manTTRIIkdMjvGDIXfuRnQSs/Duy0XEKALIs7w1UaQ+vwHre9dqQ86JcCbFi1Cl8ezcxok6CdrlETYtCboUf127glIJn/CleqJPC5j8JgPbvOLVhU4KGLRrCPw6RO+ajPDk7SlNbp2Q3qc9+pLHWjp1earOYlqA3kTXnbBbG2TY3FSszTbaHz8r2mgfa96NvKA4yjzA3hO40+osnBXFnHUjZ99wwZcBLlPYatxzUB4OLU5+7BH1jiO8mSiZsyRBbLx4Vd66gsecFhm7788s+y8aQ193XWqBnNT0xCCyz84qQ2aNXxg9mqkUH8Sz7i3aPH0KRyhi894eGBbum4t/Pm5HSSt0vWBO7tvn8bx/irJQnQzxAU+k3i/o00ja0tBpZm5sVFW6rUf1qZ9ezB4O2/jvdmeekp8LPjcoZNzV7ca74Uh/iyogr/3MIP8C4kvWGRDj0oE0/Dy67zUM2Q=
